Add a gradle compatible file namer
retest/recheck pull request #124
Opened 2019-02-28 11:03 UTC by narkaTee

A file namer which is compatible with the default gradle folder layout.

Currently it uses the hardcoded test reports path `build/test-results/test` for the result files.
The workspace path is identical to the maven file namer.

This will work with the default gradle sourceSet layout for java projects.
Gradle allows users to reconfigure the sourceSets (adding new, etc.), so this might break depending how "strange" die build config is.
I will test some scenarios and report back with the results.

2019-02-28 20:09 UTC, beatngu13 commented
First of all, thanks for the PR! I've made some adaptions here:

https://github.com/retest/recheck/compare/feature/gradle-file-namer

I've also added a test where I included the expected results. I'm not that familiar with Gradle, but I think

```
src/test/resources/resources/retest/foo/bar.recheck
build/test-results/test/foo/bar.result
```

should be

```
src/test/resources/resources/retest/recheck/foo/bar.recheck
build/test-results/test/retest/recheck/foo/bar.result
```

?

Also, feel free to include yourself in `<contributors>` within the POM.

2019-02-28 20:10 UTC, beatngu13 requested changes
See feature branch in recheck.

2019-03-03 13:02 UTC, narkaTee commented
> First of all, thanks for the PR! I've made some adaptions here:
> 
> https://github.com/retest/recheck/compare/feature/gradle-file-namer

I have added support for different gradle source sets, by allowing a source set name to passed to the namer.



> I've also added a test where I included the expected results. I'm not that familiar with Gradle, but I think
> 
> ```
> src/test/resources/resources/retest/foo/bar.recheck
> build/test-results/test/foo/bar.result
> ```
> should be
> 
> ```
> src/test/resources/resources/retest/recheck/foo/bar.recheck
> build/test-results/test/retest/recheck/foo/bar.result
> ```
> ?

Gradle only creates the folders up to `build/test-results/test/`, every folder after that has to be created by retest.

I was actually confused about who creates the folder structure `target/test-classes/retest/recheck/`, I assumed maven does that because I could not find a code path in `RecheckReplayResultUtil` that creates folders.
That is why I choose `build/test-results/test/`.

But I would also prefer `build/test-results/test/retest/recheck/`.
Maybe `RecheckReplayResultUtil.persist` could use `FileUtil.ensureFolder` to create the folders?

2019-03-05 14:54 UTC, beatngu13 approved these changes

2019-03-05 15:07 UTC, merged

2019-03-05 15:27 UTC, beatngu13 commented
Thx @narkaTee! 🙏