Feature/#159 fix terminology
retest/recheck pull request #166
Opened 2019-04-05 11:39 UTC by oezelenes

resolves#159

2019-04-05 12:26 UTC, beatngu13 requested changes
Looks good. I just wonder if this breaks compatability beyond our own projects, i.e., external API? @modulo11 @roesslerj

2019-04-05 12:26 UTC, beatngu13 commented on src/main/java/de/retest/recheck/NoGoldenMasterActionReplayResult.java
> +	private static final String MSG_SHORT = "No 'Golden Master' found.";
Needs no (single) quotes here and elsewhere.

2019-04-05 17:45 UTC, diba1013 commented
Just a reminder: Documentation

2019-04-11 07:00 UTC, beatngu13 commented
> Just a reminder: Documentation

We already use Golden Master there, but we probably should explain what is the difference between a Golden Master and a (SUT) state.

2019-04-11 07:17 UTC, beatngu13 approved these changes

2019-04-11 07:19 UTC, merged