#RET 1635 Create visibility filter file
retest/recheck pull request #171
Opened 2019-04-11 09:54 UTC by ivonx

2019-04-11 10:38 UTC, beatngu13 submitted a review, later dismissed
Same as in https://github.com/retest/recheck/pull/172.

2019-04-11 10:38 UTC, beatngu13 commented on src/main/resources/filter/web/visibility.filter
> +  #  - perspective-origin
Shouldn't this be:

```
#attribute=perspective-origin
```

Copy & paste from `attributes.yaml`? 😉

2019-04-15 19:21 UTC, roesslerj requested changes

2019-04-15 19:21 UTC, roesslerj commented on src/main/resources/filter/web/visibility.filter
> +attribute=all
I think `all` is a retest internal attribute. I don't think that is an existing CSS attribute?

2019-04-15 19:21 UTC, roesslerj commented on src/main/resources/filter/web/visibility.filter
> +attribute=value
I would add `src` and newline at end of file.

2019-04-16 08:50 UTC, roesslerj approved these changes

2019-04-16 11:05 UTC, roesslerj approved these changes

2019-04-16 11:06 UTC, merged