Issue182: Load recheck.ignore file by suite
retest/recheck pull request #193
Opened 2019-05-03 13:30 UTC by hansi-b

This pull request pertains to the first half of https://github.com/retest/recheck-web/issues/182 : 

The RetestImpl now loads a second, optional, suite-specific filter in addition to the already loaded global one.

The new suite filter is loaded from the suite's golden master directory. It is loaded with the same mechanism as the global filter (e.g., also allows for a rules file). One difference is that a missing suite filter is not logged as an error (but as a debug message).

The remaining part of issue 182 is adding the step-wise filters (called level 3 in issue 182)

2019-05-08 11:26 UTC, beatngu13 requested changes

2019-05-08 11:26 UTC, beatngu13 commented on src/main/java/de/retest/recheck/RecheckImpl.java
> +	private final Filter ignoreApplier;
I think changing the field name would also be a good idea:

```suggestion
	private final Filter filter;
```

2019-05-08 11:26 UTC, beatngu13 commented on src/main/java/de/retest/recheck/RecheckImpl.java
> +		ignoreApplier = new CompoundFilter( Lists.newArrayList( globalIgnoreApplier, suiteIgnoreApplier ) );
IMHO it is good to not rely on Guava if there is similar JDK method:

```suggestion
		ignoreApplier = new CompoundFilter( Arrays.asList( globalIgnoreApplier, suiteIgnoreApplier ) );
```

2019-05-08 11:26 UTC, beatngu13 commented on src/main/java/de/retest/recheck/review/workers/LoadFilterWorker.java
> +	private final Optional<Path> ignoreFile;
I know that this is a controversial topic, but I wouldn't use `Optional` in fields.

See Stuart Marks' (who works for the core libraries team in the JDK group at Oracle) talk "Optional – The Mother of All Bikesheds" from Devoxx 2016 at [54:04](https://www.youtube.com/watch?v=Ej0sss6cq14&feature=youtu.be&t=54m04s):

>Why Not Use Optional in Fields?
>
>* More a style issue than a correctness issue
>   * usually there's a better way to model absence of a value
>   * use of Optional in fields often arises from slavish desire to eliminate nullable fields
>   * remember, eliminating nulls isn't a goal of Optional
>* Using Optional in fields…
>   * creates another object for every field
>   * introduces a dependent load from memory on every field read
>   * clutters up your code
>   * to what benefit? ability to chain methods?

2019-05-08 11:26 UTC, beatngu13 commented on src/test/java/de/retest/recheck/RecheckImplTest.java
> +		Mockito.verify( check ).createFileNamer( "de.retest.recheck.RecheckImplTest" );
We almost always use static importants for this reduce noise.

2019-05-08 11:26 UTC, beatngu13 commented on src/test/java/de/retest/recheck/review/workers/LoadFilterWorkerTest.java
> +		assertThrows( IllegalArgumentException.class, () -> worker.load() );
We usually use AssertJ for assertions as they are—in our opinion—more flexible and readable.

2019-05-15 08:36 UTC, beatngu13 approved these changes

2019-05-15 08:59 UTC, merged

2019-05-20 16:09 UTC, hansi-b commented
Sorry, only got around to this now - thanks for the adaptations and the link to the interesting talk!