Feature/ret 1631 implement filter for diff command
retest/recheck pull request #206
Opened 2019-05-13 09:25 UTC by ivonx

2019-05-13 10:59 UTC, roesslerj requested changes

2019-05-13 10:59 UTC, roesslerj commented on src/test/java/de/retest/recheck/ignore/SearchFilterFilesTest.java
> +		final String invalidName = "color.filter";
I would split that into two tests ... this one and searchFilterByName_should_not_return_nonexistent_file mit color.filter.

2019-05-14 06:25 UTC, diba1013 requested changes

2019-05-14 06:25 UTC, diba1013 commented on src/main/java/de/retest/recheck/ignore/CompoundFilter.java
> +	public List<Filter> getFilters() {
You just need this method in a test? I think, that you could just use the Filter methods to compare [this ](https://github.com/retest/recheck.cli/pull/62/files#diff-f4a532528223635b5a54a9dadb6877ceR86). If you really need this method, make it immutable `Collections.immutableList`, maybe even within the constructor.

2019-05-14 06:25 UTC, diba1013 commented on src/main/java/de/retest/recheck/ignore/SearchFilterFiles.java
> +		for ( int j = 0; j < getAllFilterFiles().size(); j++ ) {
You are calling `getAllFilterFiles()` multiple times. Please extract a variable.

2019-05-14 06:25 UTC, diba1013 commented on src/main/java/de/retest/recheck/ignore/SearchFilterFiles.java
> +		for ( int j = 0; j < getAllFilterFiles().size(); j++ ) {
You do not need the index here. Please consider a `for-each-loop` or advanced, a stream 😄.

2019-05-14 06:25 UTC, diba1013 commented on src/main/java/de/retest/recheck/ignore/SearchFilterFiles.java
> +					return Optional.of( ignoreApplier );
We really need one method for loading filters someday...

2019-05-16 09:30 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-05-16 10:29 UTC, beatngu13 commented
Blocked by RET-1720, let's reopen afterwards.

2019-05-24 09:31 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-05-24 09:33 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-05-24 09:34 UTC, beatngu13 commented
Close until conflicts have been resolved.

2019-05-24 09:34 UTC, closed without merging