We can even do the opposite, and filter content but no CSS...
retest/recheck pull request #338
Opened 2019-07-31 21:31 UTC by roesslerj

2019-08-01 06:06 UTC, diba1013 requested changes

2019-08-01 06:06 UTC, diba1013 commented on src/main/resources/filter/web/content.filter
> +attribute=text
I don't quite get the commit message ... What are you trying to do?
As always ... We cannot just simply add `.filter`-files. They need to be registered.

2019-08-13 08:11 UTC, alig01 approved these changes

2019-08-13 08:15 UTC, diba1013 approved these changes

2019-08-13 08:16 UTC, merged