Feature/adapt no golden master
retest/recheck pull request #382
Opened 2019-08-27 07:24 UTC by diba1013

Was there any reason on why this fails if only all results are `NoGoldenMasterActionReplayResult`

2019-08-27 08:10 UTC, roesslerj submitted a review, later dismissed

2019-08-27 08:16 UTC, roesslerj requested changes
This should be (as the method name suggests) `allMatch`.

2019-08-29 10:29 UTC, diba1013 commented
Seems like Github is a bit confused, as I cannot request a new review.

2019-08-29 11:05 UTC, roesslerj approved these changes

2019-08-29 11:15 UTC, merged