Move evaluation of suite name into builder.
retest/recheck pull request #450
Opened 2019-10-01 11:03 UTC by briemla

Revert RecheckOptions to simple data holder.

2019-10-01 13:48 UTC, diba1013 commented
Looks fine to me. @beatngu13 please do the actual review as I was partly involved with this PR.

2019-10-01 15:02 UTC, beatngu13 requested changes

2019-10-01 15:02 UTC, beatngu13 commented on src/main/java/de/retest/recheck/RecheckOptions.java
> +			return new CompoundFilter( Arrays.asList( //
AFAIK `CompoundFilter` also accepts varargs, so we can omit the list.

2019-10-02 18:28 UTC, beatngu13 commented
Since you are away for the rest of the week, I did the changes. ✌️

2019-10-02 18:29 UTC, beatngu13 approved these changes

2019-10-02 18:37 UTC, merged