Feature/fix illegal reflection
retest/recheck pull request #489
Opened 2019-10-30 13:21 UTC by oezelenes

This fixes #340 and closes #340

2019-10-30 15:14 UTC, beatngu13 requested changes

2019-10-30 15:15 UTC, beatngu13 commented
@diba1013 as this fixes #340, which seems to crash tests in certain situations, it might make sense to merge this into the release branch. What do you think?

2019-11-01 07:47 UTC, diba1013 commented
As this is extremely hard to test on CI, we would need confirmation. So this can be included in the release.

Was this properly tested with the setup https://github.com/retest/recheck/issues/340#issuecomment-545035288 on Mac and different Java versions?

Don't forget the changelog.

2019-11-01 09:12 UTC, beatngu13 commented
I did a quick manual test on Mac using OpenJDK 8 and 11, where it worked. But as you said, testing this properly on CI is probably not an option.

@kema91 itensively worked on the scaling/screenshot mess in the past. I would suggest that he might have a look on it, and if everything is fine, we might want to include this as it appears to be a quite important fix?

2019-11-04 12:16 UTC, beatngu13 approved these changes

2019-11-04 12:25 UTC, merged