Fix/js filter log cache
retest/recheck pull request #498
Opened 2019-11-02 18:16 UTC by roesslerj

This fix improves logging such that we see which file contains errors and, most importantly, removes a faulty cache. If the matches function fails one time, it will never be called again. AND it's redundant functionality, as this is implemented already by the CacheFilter...

2019-11-02 22:09 UTC, diba1013 requested changes
Is this a bug or a feature (**genuine question!**)?

My understanding of the code is that once a script error is thrown (I assume through `throw new Error("Foo")` or compile errors), the method is never called again (especially in the first case), despite other parameters being used that may or may not cause an error. Is there a test that represents this behavior (i.e. throw a script error) or bug?

Do we need a changelog that says something like: 
> * Fixed that JavaScript filters where not executed again after an error has been thrown.
> * Improved log messages of faulty JavaScript filters to show the file where the error actually happened.

Secondly, do we really need a warning here, we could have sensible behavior when returning `undefined`, `null` or `not-a-boolean`? JavaScript as such is a really forgiving (scripting) language. We can either adjust for that with potential many log messages (one for each invocation with different parameters) or simply forgiving results (i.e. ignore that result).

Thirdly, this is really a two part PR. One bug fix (I assume), one feature. However, since the changes are already made and quite simple, these can be merged, considering mentioned points.

2019-11-02 22:16 UTC, roesslerj commented on src/main/java/de/retest/recheck/ignore/JSFilterImpl.java
> +	private final String filePath;
Hmm. We only need it for debugging, so all we do is call `toString()` anyways. This way we only need to call once. What do you think?

2019-11-02 22:17 UTC, roesslerj commented on src/main/java/de/retest/recheck/ignore/JSFilterImpl.java
>  	Reader readScriptFile( final Path ignoreFilePath ) {
Good catch.

2019-11-02 22:17 UTC, roesslerj commented on src/main/java/de/retest/recheck/ignore/JSFilterImpl.java
> +						callResult.getClass(), filePath );
Even better catch!

2019-11-02 22:18 UTC, roesslerj commented on src/test/java/de/retest/recheck/ignore/JSFilterImplTest.java
> +	Path ctorArg = new File( "unused" ).toPath();
I'd rather not introduce an unused tmp dir. So `Paths.get()` then.

2019-11-02 22:18 UTC, roesslerj commented on src/test/java/de/retest/recheck/ignore/JSFilterImplTest.java
> +	Path ctorArg = new File( "unused" ).toPath();
Done

2019-11-02 22:19 UTC, roesslerj commented on src/main/java/de/retest/recheck/ignore/JSFilterImpl.java
> +	private final String filePath;
I don't see a reason to prefer Path here... so I'll keep it. Agreed?

2019-11-02 22:26 UTC, roesslerj commented
As of me testing/using that functionality, this is a bugfix:
When the method is executed with different parameters, some may cause an exception (scripting language) while others may not. A single faulty call will cause this method to never be called again. 

If you want, we can try to come up with a test for that, but since we would need to go through the Caching to have something representative, I assume this isn't easy. Would like to postpone this after the release...

Changelog adapted as suggested.

2019-11-02 22:28 UTC, roesslerj commented
Ah, regarding the warning: It is already not easy to code this things, as no debugging is possible. A warning is the least we can (and should) do.

2019-11-02 22:49 UTC, diba1013 commented
> It is already not easy to code this things, as no debugging is possible

That is the downside of introducing foreign (scripting) languages within another and why (in my opinion) the JS Filters were/are a bad idea, just to make up for the lack of support of our syntax. But that's another discussion... . I agree that for that reason we kinda need logging.

> If you want, we can try to come up with a test for that, ...

I do not know nashorn that well and when such a `ScriptException` is raised. I would assume mentioned cases. If so, a test can be quite easily achieved, since we do logging, this can be quite easily catched.

Possible test cases:

1. Compile errors
2. Always throw exception, regardless of parameters
3. Conditionally throw exception (e.g. based on specific element.type)

Test behavior:

1. Write code that reliably throws a `ScriptError` if invoked (see above).
2. Invoke both possible functions (ideally in separate tests) one time. The prior behavior should have written this into the faulty list, thus never invoking the function again, thus not providing another log method.
3. Invoke the method again. With the new behavior, this should produce another log message, even for different parameters.

If this is as simple as illustrated, please implement, otherwise after the release is fine too (in which case I take no responsibilities 😄).

2019-11-04 13:58 UTC, diba1013 requested changes
Just a bump. See my [comment](https://github.com/retest/recheck/pull/498#issuecomment-549088081).

2019-11-05 08:04 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-11-05 08:06 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-11-06 08:40 UTC, diba1013 commented
We will postpone this into the next release.

2019-11-06 08:40 UTC, closed without merging

2019-11-06 14:42 UTC, roesslerj commented
So a fix of an actual bug didn't make it into the release. Wow, thanks.

2019-11-06 14:43 UTC, roesslerj commented
Shall we start a 1.6.1 release for that? 👎

2019-11-06 14:47 UTC, roesslerj commented
What happened to "Working software is the primary measure of progress." and "Our highest priority is to satisfy the customer" combined with "Individuals and interactions over processes and tools". I feel this small and essentially risk-free change with a bug-fix should have made it into the release.

2019-11-06 14:48 UTC, diba1013 commented
We decided that only fixes shall go into the release that were introduced with this release. This bug is a regression, that's why it was not merged. 

Secondly, my comments were not addressed in time and I did not want to postpone the release.

2019-11-06 15:16 UTC, martin-v commented
We agreed that we want to release more often, if we still add as "default process" bug fixes and features in each release branch this will not happen. We should explicitly change our release process if it no longer fits and not violating it each time.

We tested the release the last 2 days and we considered it as stable that is why it is released. We can make another release soon, or a hofix if it's a blocker bug. This is better than adding a change testing the artefact again 2 days and then adding another bugfix and testing again ..., in the meantime the release branch and the develop branch differs more and more.

2019-11-18 19:42 UTC, roesslerj commented
> That is the downside of introducing foreign (scripting) languages within another and why (in my opinion) the JS Filters were/are a bad idea, just to make up for the lack of support of our syntax. But that's another discussion... . I agree that for that reason we kinda need logging.

This is indeed another discussion and has nothing to do with this PR.

I just re-read the suggested test cases. Although I agree in general, that these could be added, I fail to see how the current changes warrant such excessive added tests. After all, we agreed to keep PRs small and not ask too much of a single change (https://retest.atlassian.net/wiki/spaces/RET/pages/4961437/Changing+things+including+GUI). Too bad this change didn't make it into the release... and unnecessarily so.

2019-11-18 20:03 UTC, roesslerj commented
> That is the downside of introducing foreign (scripting) languages within another and why (in my opinion) the JS Filters were/are a bad idea, just to make up for the lack of support of our syntax. But that's another discussion... . I agree that for that reason we kinda need logging.

This is indeed another discussion and has nothing to do with this PR.

I just re-read the suggested test cases. I fail to see how the current changes warrant these tests. After all, the goal of this change was not to produce the same log message all over again, but to defer that functionality to the CacheFilter, for which tests already exist. I do not see how it makes sense to write tests for _removed_ behavior and even use log-messaging for checking the change. This is not in spirit of TDD and IMHO a very good _counter-example_ of a change that is not reflected in tests.

Also, we agreed to keep PRs small and not ask too much of a single change (https://retest.atlassian.net/wiki/spaces/RET/pages/4961437/Changing+things+including+GUI). Too bad this change didn't make it into the release... and unnecessarily so.

2019-11-18 20:04 UTC, roesslerj commented
One could argue that there should have been a test that makes sure a method doesn't get called twice and this PR would then remove this test.

2019-11-18 20:48 UTC, diba1013 commented
I want to cite following lines:

> Fixed that JavaScript filters where not executed again after an error has been thrown.
> If you want, we can try to come up with a test for that [...] this isn't easy.
> I fail to see how the current changes warrant these tests.

I was just trying to come up with test cases that assume an exception be thrown, as suggested by you. This PR claims to fix a bug where if the JS throws an exception, the method is not called again. Funnily enough, since you mention TDD: What test did you write to verify the bug and later on verify that it has been solved? This has clearly not been tested before, otherwise there would have been no such bug. As of now, I cannot see a any test case that really verifies that this issue has been resolved by throwing an exception, or a similar test case which I tried to describe in the above mentioned comments. Thus I would have to manually verify this bug has been resolved within the release, requiring manual labor in order for that changelog entry being justified.

> Also, we agreed to keep PRs small and not ask too much of a single change

Yes, I know. However that is no excuse of missing tests as stated by our DoD which is conveniently incorporated in the default PR template within GitHub. _Please see my notes below_.

---

Regardless, I was simply [asking for your opinion](https://github.com/retest/recheck/pull/505#pullrequestreview-312487572) on the matter in the re-opened #505, and you presented it to me. With that in mind, I will approve, quoting your response, so that it can at least make it in the next release and is not stalled by formalities or missing tests.

Please note, however, that I hold my comment in that I take no responsibility in the aforementioned case.

2019-11-18 21:10 UTC, roesslerj commented
I added a test that proves that there was a bug (when executed with unaltered code) and now passes.