Temp commit
retest/recheck pull request #514
Opened 2019-11-13 13:24 UTC by oezelenes

Draft pull request for feedback from @diba1013

2019-11-15 15:12 UTC, diba1013 requested changes
Please evaluate the usages of ActionReplayResult and guess the time, we would need for an update branch to adjust to these changes (with the deleted methods and such). Secondly, please guess the work in creating/updating tests for each of the specialized class. 

Is the time we need to invest worth it for this change?

Also, please cleanup your commit history 😄

2019-11-15 15:12 UTC, diba1013 commented on src/main/java/de/retest/recheck/report/ResultWithDeletion.java
> +public class ResultWithDeletion extends ActionReplayResult {
JAXB needs a default constructor to deserialize the class.

2019-11-15 15:12 UTC, diba1013 commented on src/main/java/de/retest/recheck/report/ResultWithError.java
> +public class ResultWithError extends ActionReplayResult {
Upon looking at the usages, is it even possible for a ResultWithError to be constructed? As its only usage is in the `TestReportFilter`. You even made the constructor package private.

If not, can we delete this class completely? 😄 TNFE Flashbacks...

2019-11-20 09:39 UTC, oezelenes commented on src/main/java/de/retest/recheck/report/TestReplayResult.java
> -	public Set<LeafDifference> getDifferences( final Filter filter ) {
There is no active usage for this method in review.

2019-11-20 09:41 UTC, oezelenes commented on src/main/java/de/retest/recheck/review/AcceptableElementDifference.java
> +						.addAll( ((IdentifyingAttributesDifference) difference).getAttributeDifferences() );
Yes I do. It seems like this is proper formatting for the plugin, because of the cast.

2019-11-29 14:28 UTC, diba1013 requested changes

2019-11-29 14:28 UTC, diba1013 commented on src/main/java/de/retest/recheck/report/ActionReplayResult.java
> +
It seems that this line break was unintentional.

2019-11-29 14:28 UTC, diba1013 commented on src/main/java/de/retest/recheck/report/ActionReplayResult.java
> +		if ( windows.isNull() && difference.isNull() ) {
Could you reorder this constructor to the other constructor (i.e. above the static functions) ?

2019-11-29 14:28 UTC, diba1013 commented on src/test/java/de/retest/recheck/report/ActionReplayResultTest.java
> -	void getDiffrences_should_ignore_path_changes() {
Did those tests have been accidentally been removed?

2019-11-29 14:28 UTC, diba1013 commented on src/test/java/de/retest/recheck/report/ActionReplayResultTest.java
> -		final List<RootElementDifference> differences = Arrays.asList( //
Seems to be a formatting issue

2019-11-29 14:28 UTC, diba1013 commented on src/main/java/de/retest/recheck/printer/ActionReplayResultPrinter.java
> +
It seems that this line break was unintentional.

2019-11-29 14:28 UTC, diba1013 commented on src/main/java/de/retest/recheck/report/ActionReplayResult.java
> +	private static final long serialVersionUID = 2L;
Didn't we also want to increase the `TestReport#PERSISTENCE_VERSION`?

2019-12-06 11:13 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:14 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:16 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:17 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:19 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:20 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:21 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:23 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:24 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:26 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:27 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:29 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:30 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:32 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:33 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:34 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:36 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:37 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:39 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:40 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:42 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:43 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:45 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:46 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:47 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:49 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:50 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:52 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:53 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...

2019-12-06 11:55 UTC, beatngu13 commented
Close until conflicts have been resolved.

2019-12-06 11:55 UTC, closed without merging

2019-12-06 11:55 UTC, rebazer commented
Rebase failed, this pull request needs some manual love ...