Refactor alignment
retest/recheck pull request #567
Opened 2019-12-10 12:31 UTC by beatngu13

I will update this draft while I try to better understand the `Alignment` class. Please let me know if there is something you wouldn't change/refactor.

2019-12-10 13:36 UTC, beatngu13 commented
Oh and you better go commit by commit, the overall diff is awful.

2019-12-16 08:12 UTC, beatngu13 commented
[nudge reviewer]

2019-12-16 12:21 UTC, roesslerj requested changes

2019-12-16 12:23 UTC, beatngu13 commented on src/main/java/de/retest/recheck/ui/diff/Alignment.java
> +		final Queue<Element> elementsToAlign = toReverseQueue( expectedElements );
I added this reference to the commit message:

https://stackoverflow.com/a/30389890

Makes sense to me, what do you say?

2019-12-16 12:25 UTC, beatngu13 commented on src/main/java/de/retest/recheck/ui/diff/Alignment.java
> +		final Queue<Element> elementsToAlign = toReverseQueue( expectedElements );
Oh and we reverse the stack too, it just wasn't reflected in the method name: https://github.com/retest/recheck/blob/master/src/main/java/de/retest/recheck/ui/diff/Alignment.java#L168

2019-12-16 12:26 UTC, beatngu13 commented on src/main/java/de/retest/recheck/ui/diff/Alignment.java
> +		final Queue<Element> elementsToAlign = toReverseQueue( expectedElements );
(Just realized I should use `Deque` …)

2019-12-16 14:05 UTC, roesslerj commented on src/main/java/de/retest/recheck/ui/diff/Alignment.java
> +		final Queue<Element> elementsToAlign = toReverseQueue( expectedElements );
Wanna push a Dequeue? Then I'll approve :-)

2019-12-16 18:44 UTC, roesslerj approved these changes

2019-12-16 18:44 UTC, merged