Do not append to the file, as this will double its content each time...
retest/recheck pull request #615
Opened 2020-01-23 15:34 UTC by roesslerj

2020-01-23 15:40 UTC, diba1013 requested changes

2020-01-24 08:18 UTC, roesslerj commented on src/main/java/de/retest/recheck/review/workers/SaveFilterWorker.java
> -		try ( final PrintStream writer = new PrintStream( FileUtils.openOutputStream( ignoreFile ) ) ) {
Right. I messed up my testing, this doesn't fix this. Good catch. But how is the line below the cause?

2020-01-24 08:31 UTC, roesslerj commented
Dang. Da wird nicht appended. Da wird eine andere Datei mit dazu geschrieben ... weil wir die Source der Filter nicht trennen...

2020-01-24 08:31 UTC, closed without merging

2020-01-24 08:37 UTC, diba1013 commented on src/main/java/de/retest/recheck/review/workers/SaveFilterWorker.java
> -		try ( final PrintStream writer = new PrintStream( FileUtils.openOutputStream( ignoreFile ) ) ) {
If this is really a problem, and I do not think, this is the cause (upon reflection, I was just confused what you did here), you could use:
```
FileUtils.writeLines(File, Collection<String>)
Files.write(Path, Iterable<CharSequence>)
```
Make sure to add a test and that the file is created.