Fix Mergify config
retest/recheck pull request #648
Opened 2020-02-08 12:25 UTC by beatngu13

@roesslerj pointed out that Mergify sometimes merges base into head, rather than rebasing head against base. This fix should solve this issue and also introduces less-verbose rule names.

@diba1013 we already talked about this a few weeks ago. Any other ideas? We should also keep an eye on this before adopting Mergify elsewhere. However, as soon as this is merged, I will update the other configs accordingly.

2020-02-08 13:20 UTC, diba1013 requested changes
Just to recap:

We want all branches up to date prior to merging. We have following use cases:
1. If non-release (into either master/release): rebase onto base, then merge.
2. If release (into master): merge base into head, then merge.

My question is: "Do we still need the rebase if the review is pending?". As this essentially is the cause for the rebase/merge conflict. 

If I recall our processes from the past, we just rebased to make it easier to merge by allowing the reviewer to simply press the merge button (as it will be always up to date) or to know if there are conflicts (which a good git diff will show anyways). We kept this for the rebazer so that it knows and can comment if there are conflicts. But since we always make sure that the branches are up to date just before merging, can we get rid of the rebase while the review is pending and just rebase once prior to merging?

Following use cases come to mind, if we rebase to keep the branch up to date:

1. rebase successful: No action needed.
2. review approved, rebase fails: author needs to manually do the rebase and resolve the conflict. The reviewer is unlikely to verify these changes afterwards (as we do not remove the approval if there are conflicts.
3. review pending, rebase fails: this is displayed in the checks (to my knowledge) and either the autor or the reviewer can simply request changes to resolve the conflicts.

If there are multiple PRs approved at the same time, one can hardly predict if there are conflicts.

@martin-v Am I missing something?

---

Either way, we could try to stop a merge if there are conflicts:

```yml
condition:
  - conflict=true
actions:
  comment:
    message: This PR needs some manual love. # Or similar
  dismiss_reviews:
    approved: true
    message: The author needs to resolve conflicts. Please re-review afterwards.  
```

2020-02-08 13:50 UTC, beatngu13 commented on .mergify.yml
> +  - name: 'rebase unreviewed non-release PRs'
Hmmm, I don't know. Even if Mergify doesn't handle this properly, Git/GitHub does. In the worst case, the same rebase happens twice I guess?

Anyways, what condition would you suggest?

2020-02-08 13:58 UTC, beatngu13 commented
>My question is: "Do we still need the rebase if the review is pending?".

Otherwise PRs without a review won't be up-to-date, only right before the merge. Then a review might happen on an outdated branch.

The rebazer also did rebase unreviewed PRs:

https://github.com/retest/rebazer/blob/develop/src/main/java/org/retest/rebazer/RebazerService.java#L68

2020-02-10 10:27 UTC, diba1013 commented on .mergify.yml
> +  - name: 'rebase unreviewed non-release PRs'
Maybe only rebase if review pending (i.e. invert the merge condition)? 
```
- "#approved-reviews-by<=0"
- "#changes-requested-reviews-by<=0"
```
I'm still unsure if we need the operator `=` or `<=`

2020-02-10 12:28 UTC, diba1013 approved these changes

2020-02-10 13:43 UTC, diba1013 commented
@beatngu13 You'll have to manually merge this.

2020-02-10 14:13 UTC, merged