Add metadata for web, that should also be ignored on default...
retest/recheck pull request #756
Opened 2020-07-06 11:16 UTC by roesslerj

The name of the filter (metadata.filter) suggests that it filters all meta-data. So it should also filter recheck-web metadata. As far as I know, this hasn't made it to the docs yet, so...

2020-07-06 11:28 UTC, diba1013 requested changes
The intention behind the basic implementation was to establish sensible defaults, not to exclude everything. Particularly, it should ignore ever-changing attributes (time, ...), but keep important attributes, since they may be the cause for the changes (i.e. browser name changed).

To use other words, the implementation was focused to keep the current implementation (1.11.0) which still reports the important attributes. I would urge that the user specify any additional attributes themselves.

I understand the confusion and wanted to keep the name as simple as possible (for the general, use cases) but I think that I would prefer to have a separate filter file for all metadata e.g. `metadata-all.filter`.

2020-07-06 11:30 UTC, roesslerj commented
Hmm. How about `default-metadata.filter` and `metadata.filter`, where the first is default-included in the `recheck.ignore` file and the latter ignores all metadata?

2020-07-06 11:43 UTC, diba1013 commented
> Hmm. How about default-metadata.filter and metadata.filter, where the first is default-included in the recheck.ignore file and the latter ignores all metadata?

Something along this line, maybe emphasize the volatile-ness of the attributes (e.g. `metadata-volatile.filter`). I prefer to have the metadata as first to directly specify the type (see bootstrap `btn-primary`), but I will leave that up to you. Be sure to update the documentation as outlined in retest/docs#114 and the `default-recheck.ignore`.

2020-07-07 10:55 UTC, diba1013 requested changes
I forgot to mention that you should update the changelog entry as well...

2020-07-07 10:55 UTC, diba1013 commented on src/main/resources/filter/metadata.filter
>  attribute=time.zone
Now you could use `import: volatile-metadata.filter` here too 😄

2020-07-07 10:55 UTC, diba1013 commented on src/test/java/de/retest/recheck/RecheckImplIT.java
> +	static final Filter METADATA_FILTER = Filters.parse( "import: volatile-metadata.filter" );
As seen in #757, I changed that to exclude all metadata, so this can left as `metadata.filter` (optional).

2020-07-08 08:24 UTC, diba1013 approved these changes

2020-07-08 08:29 UTC, merged