Feature/preparation-recheck-cli
retest/recheck pull request #76
Opened 2019-02-04 14:41 UTC by kema91

2019-02-04 15:09 UTC, beatngu13 commented
Is this code simply copied from retest or does it contain additional changes?

2019-02-04 15:17 UTC, kema91 commented
Mainly copied from retest-core with few adjustments. You can see the adjustments in the commit history.

2019-02-04 16:55 UTC, beatngu13 requested changes

2019-02-04 16:55 UTC, beatngu13 commented on src/test/java/de/retest/suite/flow/ApplyChangesToStatesFlowTest.java
> +	private static final Logger logger = LoggerFactory.getLogger( ApplyChangesToStatesFlowTest.class );
I think we can remove the logger from the test class.

2019-02-04 16:55 UTC, beatngu13 commented on src/test/java/de/retest/suite/flow/ApplyChangesToStatesFlowTest.java
> +	private static final String FILE = "target/test-classes/recheck/" + SUITE + "/" + TEST + "." + ACTION + ".recheck";
The file, respectively, workspace should point to a [temporary folder](https://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html).

2019-02-04 16:55 UTC, beatngu13 commented on src/main/java/de/retest/suite/flow/ApplyChangesToStatesFlow.java
> +	public List<String> apply( final SuiteChangeSet acceptedChanges ) throws NoStateFileFoundException {
The object methods can be `private` I think since there is no `public` ctor.

2019-02-04 16:55 UTC, beatngu13 commented on src/main/java/de/retest/suite/flow/ApplyChangesToStatesFlow.java
> +	public static List<String> apply( final Persistence<SutState> persistence, final SuiteChangeSet acceptedChanges )
Should be `applyChangesToStates` if we follow the naming scheme in `CreateChangesetForAllDifferencesFlow`.

2019-02-04 16:55 UTC, beatngu13 commented on src/main/java/de/retest/suite/flow/ApplyChangesToStatesFlow.java
> +	public static List<String> apply( final Persistence<SutState> persistence, final SuiteChangeSet acceptedChanges )
Or we stick to `apply`, but then it should be `CreateChangesetForAllDifferencesFlow#create(...)`.

2019-02-06 12:25 UTC, beatngu13 approved these changes

2019-02-06 12:26 UTC, merged